# Generated by Django 4.1 on 2023-01-04 09:29

from django.db import migrations, models
import django.utils.timezone
import example.application.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyOtherModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='MyModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('myCharField', models.CharField(blank=True, max_length=25, null=True)),
                ('myBooleanField', models.BooleanField(default=True)),
                ('myJsonField', models.JSONField(default=example.application.models.default_json)),
                ('myDateField', models.DateField(default=django.utils.timezone.now)),
                ('myDateTimeField', models.DateTimeField(default=django.utils.timezone.now)),
                ('myDecimalField', models.DecimalField(decimal_places=2, default=0.2, max_digits=4)),
                ('myManyToManyField', models.ManyToManyField(to='application.myothermodel')),
            ],
        ),
    ]
